# Generated by Django 4.2.27 on 2026-01-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否管理员评论'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否管理员发布'),
        ),
    ]
